version: "3"

services:
  pgsql_study:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgsql_db:/var/lib/postgresql/data
    container_name: pgsql_study
